### ISSUE TITLE
Spark structured streaming goes in infinite loop

### ISSUE THREAD

**Issue by VikramBPurohit** [qubole/kinesis-sql#19] opened 2018-09-07 15:17 UTC
When using this library to read stream from kinesis, spark goes in infinite loop. 

In our code - we are using spark structured streaming to read published events from kinesis. Although, we have published only one event - kinesis-sql code reads the same event again and again and never finish reading the same message which makes our executor node goes in recurssion.

Any idea, what could be the problem? 

@itsvikramagr

**Comment by itsvikramagr** [comment] 2018-09-10 10:36
@VikramBPurohit - can you send the checkpointed data for last few batches. Also do you know how many micro-batches were executed?
you can find it in <checkpointing-location>/offsets

**Comment by VikramBPurohit** [comment] 2018-09-11 21:31
@itsvikramagr : Thanks for your response. Looks like, the issue isn't reproducible any more and we aren't sure why it was happening? 
To your question: it was the very first micro batch which got into infinite loop

**Comment by itsvikramagr** [comment] 2018-09-12 04:13
#21 seems to be duplicate of this issue. Closing this so that we can track the problem in one place.

**Closed by itsvikramagr** 2018-09-12 04:13 UTC
