### ISSUE TITLE
Null Pointer Exception in intermittent micro batches

### ISSUE THREAD

**Issue by VikramBPurohit** [qubole/kinesis-sql#21] opened 2018-09-11 21:29 UTC
Hi @itsvikramagr 

We are getting null pointer exception in our micro batches (spark structure streaming). We are using S3 as check-point with trigger interval of 1 second.

2018-09-11 20:08:24 ERROR MicroBatchExecution:91 - Query [id = a87275fe-875f-41bf-a892-57602f8385b8, runId = f8dce2f3-7efd-4cbf-b04f-d0b2e5f769a3] terminated with error
java.lang.NullPointerException
    at org.apache.spark.sql.kinesis.KinesisSource.prevBatchShardInfo(KinesisSource.scala:216)
    at org.apache.spark.sql.kinesis.KinesisSource.getOffset(KinesisSource.scala:105)
    at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$5$$anonfun$apply$5.apply(MicroBatchExecution.scala:268)
    at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$5$$anonfun$apply$5.apply(MicroBatchExecution.scala:268)
    at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:271)
    at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
    at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$5.apply(MicroBatchExecution.scala:267)
    at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$5.apply(MicroBatchExecution.scala:264)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$constructNextBatch(MicroBatchExecution.scala:264)
    at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:128)
    at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:121)
    at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:121)
    at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:271)
    at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
    at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:121)
    at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
    at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:117)
    at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:279)
    at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:189)

**Comment by hudsonmd** [comment] 2018-09-11 21:38
To add onto this, we have verified that we can create all checkpoint directories/files necessary and do have contents in the offsets and sources directories of the checkpoint. We also have verified that the functionality can continue to work after loading from these S3 checkpoints, however, once we encounter this issue we are stuck with the null-pointer exception even after reruns and we've even seen the null-pointer exception continue after wiping the S3 checkpoint and letting it recreate a new one from scratch.

**Comment by itsvikramagr** [comment] 2018-09-12 04:11
@hudsonmd, @VikramBPurohit - thanks for reporting the issue. This looks like an issue with S3 eventual consistency. 

Executors after each micro-batch (say id =x) will commit a file in the sub-directory `x/shard-commits`
When next micro-batch (x+1) starts, the driver tries to read from the previously committed file. We are seeing an error during this step

We can possibly check the following
-  For last executed batch-id x, do we have commits for each shard in the sub-directory  `x/shard-commits`
- can we try to increase the trigger interval from 1 sec to say 30 secs or 1 minute? and see if you are seeing the same issue

If you can send me the dump of your checkpointed folder, I can also take a look into it.

There are two solutions if this is an issue with EC
-  We can modify the https://github.com/qubole/kinesis-sql/blob/master/src/main/scala/org/apache/spark/sql/kinesis/HDFSMetadataCommitter.scala to handle EC more gracefully
-  We can implement `https://github.com/qubole/kinesis-sql/blob/master/src/main/scala/org/apache/spark/sql/kinesis/MetadataCommitter.scala` for any other storage system - say for dynamoDB?

**Comment by VikramBPurohit** [comment] 2018-09-12 12:57
Thanks @itsvikramagr  for your response! We are suspecting the same problem as well. For now, we have increased our trigger interval from 1 second to 60 seconds. 

Unfortunately, S3's eventual consistency might cause this issue in future since we have seen lag of read for about 7 mins.

**Comment by itsvikramagr** [comment] 2018-09-14 04:42
Have you tried using HDFS as checkpointing location? Were you able to run your application?

**Comment by memosstilvi** [comment] 2018-09-20 16:26
Implementing the `MetadataCommitter` for `DynamoDB` would be great.
We are facing a lot of failures due to S3's eventual consistency as well.

**Comment by itsvikramagr** [comment] 2018-09-20 17:14
upcoming Spark 2.4 has provided some abstraction which we can use to directly write to S3 and avoid EC issues. We can first try to use that abstraction for our use case. This way we can also avoid dynamoDb cost as well and handles EC issue. cc @memosstilvi @VikramBPurohit 

P.S - In our Spark streaming on Qubole platform, we have ported the abstraction and implemented the direct write for checkpointing and state management. I can try to make a similar change in kinesis sql library as well

**Comment by memosstilvi** [comment] 2018-09-21 07:16
@itsvikramagr thanks for the quick response. Yeah that's something that would work for us.

**Comment by pekzeki** [comment] 2019-01-11 13:50
Hi @itsvikramagr, is there any plan for implementing a MetadataCommitter for **dynamoDB** in the 2.4.0 release?

**Comment by itsvikramagr** [comment] 2019-01-15 15:55
@pekzeki - I was hoping someone from the community can implement that. I can help in the design and code review.

For the time being, I am planning to add support to handle EC issue when HDFSMetadataCommitter is used. Hopefully, that will help in reducing null pointer exception to a great extent. Will soon start a PR for that.

**Comment by aravindgopall** [comment] 2019-01-22 13:33
any updates on this issue, we are also facing this issue with latest spark

**Comment by itsvikramagr** [comment] 2019-01-22 16:50
@aravindgopall - just to confirm you are facing the issue when the checkpointing folder is an S3 location? 

I am about to complete the code to handle EC issue with S3 and hope to start a PR soon.

**Comment by dchinu97** [comment] 2019-01-24 10:56
java.lang.IllegalStateException: Gave up after 3 retries while fetching MetaData, last exception: 
	at org.apache.spark.sql.kinesis.HDFSMetadataCommitter$$anonfun$withRetry$2.apply(HDFSMetadataCommitter.scala:241)
	at org.apache.spark.sql.kinesis.HDFSMetadataCommitter$$anonfun$withRetry$2.apply(HDFSMetadataCommitter.scala:241)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.kinesis.HDFSMetadataCommitter.withRetry(HDFSMetadataCommitter.scala:240)
	at org.apache.spark.sql.kinesis.HDFSMetadataCommitter.get(HDFSMetadataCommitter.scala:150)
	at org.apache.spark.sql.kinesis.KinesisSource.prevBatchShardInfo(KinesisSource.scala:221)
	at org.apache.spark.sql.kinesis.KinesisSource.getOffset(KinesisSource.scala:111)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$constructNextBatch$1$$anonfun$5$$anonfun$apply$9.apply(MicroBatchExecution.scala:345)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$constructNextBatch$1$$anonfun$5$$anonfun$apply$9.apply(MicroBatchExecution.scala:345)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$constructNextBatch$1$$anonfun$5.apply(MicroBatchExecution.scala:344)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$constructNextBatch$1$$anonfun$5.apply(MicroBatchExecution.scala:341)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$constructNextBatch$1.apply$mcZ$sp(MicroBatchExecution.scala:341)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$constructNextBatch$1.apply(MicroBatchExecution.scala:337)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$constructNextBatch$1.apply(MicroBatchExecution.scala:337)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.withProgressLocked(MicroBatchExecution.scala:554)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$constructNextBatch(MicroBatchExecution.scala:337)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:183)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:160)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:279)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:189)

**Comment by itsvikramagr** [comment] 2019-01-24 11:23
@dchinu97 - can you confirm that the file, that the code is looking for, actually exists in s3. Basically is it a real error that file does not exist or is it an EC issue that file becomes available after some time. If its an EC issue, you may want to increase the retry count using `executor.metadata.hdfs.numretries`

**Comment by dchinu97** [comment] 2019-01-24 14:58
I am getting this error without even checkpointing to s3.I am deploying spark application on kube.I checked dynamoDB ,No meta data is stored about shards.When i was not using structured streaming meta data of shards was getting stored in DyanamoDB but now it is not getting stored.

**Comment by itsvikramagr** [comment] 2019-01-25 04:04
@dchinu97 - as mentioned before, Structured Streaming is different from earlier spark streaming which also gave us the opportunity to save dynamoDb cost and setup. You can read about design details [here](https://docs.google.com/presentation/d/1eSX7WiZxkjRy5ZDXAKRUDIKWqhP3ob2A1L1lat2QIXY/edit)

Can you use S3 location for checkpointing and rerun your application?

**Comment by dchinu97** [comment] 2019-01-25 07:52
Increased the  executor.metadata.hdfs.numretries to 20 still getting the same error.

**Comment by dchinu97** [comment] 2019-01-25 10:04
Last Shard commit folder present in s3 is "15" and i get an error stating shard-commit/16 does not exist

**Comment by dchinu97** [comment] 2019-01-25 11:05
I think the problem is with logic of previous batchID. When i deleted all the offset and shard-commit data present in s3 application worked with s3 Checkpointing.

**Comment by pekzeki** [comment] 2019-02-01 09:41
Unfortunately, the error is not easy to reproduce. I faced with EC errors just 2-3 times in a month in an application heavily uses S3. However, the patch seemed clear to me. Next week I will try, thanks.

**Comment by itsvikramagr** [comment] 2019-02-05 05:50
resolved via #41

**Closed by itsvikramagr** 2019-02-05 05:50 UTC
