### ISSUE TITLE
Error while Fetching Shard Iterator

### ISSUE THREAD

**Issue by xiaohan2013** [qubole/kinesis-sql#11] opened 2018-07-27 02:46 UTC
18/07/27 10:38:14 WARN KinesisSourceRDD: Neither LastSequenceNumber nor LastTimeStamp was recorded.
18/07/27 10:38:14 ERROR Executor: Exception in task 0.0 in stage 120.0 (TID 330)
java.lang.IllegalStateException: Error while Fetching Shard Iterator
	at org.apache.spark.sql.kinesis.KinesisReader.org$apache$spark$sql$kinesis$KinesisReader$$retryOrTimeout(KinesisReader.scala:222)
	at org.apache.spark.sql.kinesis.KinesisReader$$anonfun$3.apply(KinesisReader.scala:106)
	at org.apache.spark.sql.kinesis.KinesisReader$$anonfun$3.apply(KinesisReader.scala:106)
	at org.apache.spark.sql.kinesis.KinesisReader.runUninterruptibly(KinesisReader.scala:188)
	at org.apache.spark.sql.kinesis.KinesisReader.getShardIterator(KinesisReader.scala:104)
	at org.apache.spark.sql.kinesis.KinesisSourceRDD$$anon$1.getShardIterator(KinesisSourceRDD.scala:123)
	at org.apache.spark.sql.kinesis.KinesisSourceRDD$$anon$1.getNext(KinesisSourceRDD.scala:139)
	at org.apache.spark.sql.kinesis.KinesisSourceRDD$$anon$1.getNext(KinesisSourceRDD.scala:115)
	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:73)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:234)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:228)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:827)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:827)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.spark.sql.kinesis.shaded.amazonaws.services.kinesis.model.InvalidArgumentException: The timestampInMillis parameter cannot be greater than the currentTimestampInMillis. timestampInMillis: 1532659093716, currentTimestampInMillis: 1532659091607 (Service: AmazonKinesis; Status Code: 400; Error Code: InvalidArgumentException; Request ID: 370a77ae-1ec2-4e9d-a61e-abccb99485cd)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1586)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1254)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:747)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:721)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:704)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:672)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:654)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:518)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.services.kinesis.AmazonKinesisClient.doInvoke(AmazonKinesisClient.java:1805)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:1781)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.services.kinesis.AmazonKinesisClient.getShardIterator(AmazonKinesisClient.java:980)
	at org.apache.spark.sql.kinesis.KinesisReader$$anonfun$3$$anonfun$apply$1.apply(KinesisReader.scala:107)
	at org.apache.spark.sql.kinesis.KinesisReader$$anonfun$3$$anonfun$apply$1.apply(KinesisReader.scala:107)
	at org.apache.spark.sql.kinesis.KinesisReader.org$apache$spark$sql$kinesis$KinesisReader$$retryOrTimeout(KinesisReader.scala:212)
	... 23 more

**Comment by xiaohan2013** [comment] 2018-07-27 02:56
I don't know the reason that the exception 'The timestampInMillis parameter cannot be greater than the currentTimestampInMillis'  cause.

**Comment by itsvikramagr** [comment] 2018-07-27 06:29
@xiaohan2013 - This is a genuine error. It might be related to https://github.com/qubole/kinesis-sql/issues/3 

I suspect this error is due to some difference in system clock time. Did you see this error during the first execution of the micro-batch or at a later stage?

**Comment by itsvikramagr** [comment] 2018-09-10 15:45
Closing this since #3 would fix such issues.

**Closed by itsvikramagr** 2018-09-10 15:45 UTC

**Comment by OlhaShopback** [comment] 2019-04-22 09:49
It is reproducible for second stage in my case.
